# Generated by Django 3.2 on 2022-07-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0020_auto_20220725_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(default=0.0)),
                ('total_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('services', models.ManyToManyField(blank=True, null=True, related_name='services', to='barbershop.Service')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.worker')),
            ],
        ),
    ]
