# Generated by Django 3.2 on 2022-08-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
