version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000 
    volumes:
      - ./barber:/barber 
    command: sh -c "python manage.py wait_for_db
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=somesecret
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=barberdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - EMAIL_HOST_USER=chopbarberdemo@gmail.com
      - EMAIL_HOST_PASSWORD=ftevxxqehqzppflk
      - DEFAULT_FROM_EMAIL=chopbarberdemo@gmail.com
    depends_on:
      - db 
      - redis
      - celery_worker

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=barberdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7-alpine
    expose: 
      - '6379'
    ports:
      - '6379:6379'

  celery_worker:
    build:
      context: .
    image: django_celery_worker
    command: celery -A barber worker -l info --pool=solo
    volumes:
      - ./barber:/barber
    depends_on:
      - redis
      - db