# Generated by Django 3.2 on 2022-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
