# Generated by Django 3.2 on 2022-07-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_alter_service_estimated_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='estimated_time',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
