# Generated by Django 3.2 on 2022-07-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_alter_worker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='expertise',
            field=models.CharField(blank=True, choices=[('MENS', "Men's cuts"), ('WOMENS', "Women's cuts"), ('SHAVING', 'Shaving'), ('KIDS', "Kids' cuts")], max_length=100, null=True),
        ),
    ]
