# Generated by Django 3.2 on 2022-07-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_alter_worker_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
