# Generated by Django 3.2 on 2022-07-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_alter_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='barbershop.Service'),
        ),
    ]
