# Generated by Django 3.2 on 2022-07-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0010_alter_client_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='expertise',
        ),
        migrations.AddField(
            model_name='worker',
            name='expertise',
            field=models.ManyToManyField(blank=True, null=True, related_name='expertise', to='barbershop.Service'),
        ),
    ]
