# Generated by Django 3.2 on 2022-07-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0011_auto_20220719_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
