# Generated by Django 3.2 on 2022-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0012_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='barbershop/workers/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('SCISSORSHARICUT', 'Scissors haircut'), ('CLIPPERHAIRCUT', 'Clipper Haircut'), ('BEARDCUT', 'Beard Cut'), ('STYLING', 'Styling'), ('BROWCORRECTION', 'Brow Correction'), ('COMBINEDCUT', 'Combined Haircut'), ('BUDDYPLUSBUDDY', 'Buddy + Buddy')], max_length=100),
        ),
    ]
