# Generated by Django 3.2 on 2022-07-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0015_auto_20220721_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='working_dates',
        ),
        migrations.AddField(
            model_name='worker',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='barbershop.Schedule'),
        ),
    ]
