# Generated by Django 3.2 on 2022-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0016_auto_20220721_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
    ]
