# Generated by Django 3.2 on 2022-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0018_alter_appointment_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('E', 'Evening')], max_length=2, null=True),
        ),
    ]
