# Generated by Django 3.2 on 2022-07-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0020_auto_20220725_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
