# Generated by Django 3.2 on 2022-07-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0022_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='_free_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
