# Generated by Django 3.2 on 2022-07-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0024_worker_free_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='_free_dates',
            new_name='_dates_listed',
        ),
    ]
