# Generated by Django 3.2 on 2022-07-28 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0026_schedule_date_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_for',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
