# Generated by Django 3.2 on 2022-08-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0029_auto_20220803_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerschedule',
            old_name='free_dates',
            new_name='_dates_listed',
        ),
    ]
