# Generated by Django 3.2 on 2022-08-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0031_rename__dates_listed_workerschedule_dates_listed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='_dates_listed',
            new_name='dates_listed',
        ),
    ]
