# Generated by Django 3.2 on 2022-08-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0032_rename__dates_listed_schedule_dates_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.location'),
        ),
    ]
