# Generated by Django 3.2 on 2022-08-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0033_worker_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
