# Generated by Django 3.2 on 2022-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0034_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
